In [16]:
import pickle 

with open('VEC_target_feats.pkl', 'rb') as f:
    x = pickle.load(f, encoding='utf-8')
print(type(x))
print(x)
print(x.keys())
print(len(x['Gene_enco']))
print(type(x['Gene_enco']))
print(x['Gene_enco'])
print(x['Gene_enco'].dtype)
b = x['Gene_enco'].astype(int)
print(b)
print(b.dtype)

# import numpy as np

# def convert_to_nan(array, value):
#     array = array.astype(np.float64)  # Convert the array to float64 to accommodate NaN
#     array[array == value] = np.nan   # Replace the specific value with NaN
#     return array

# # Example usage:
# input_array = np.array([1.5, 2.7, 3.2, -9223372036854775808, 4.9])
# value_to_convert = -9223372036854775808

# b = convert_to_nan(b, value_to_convert)
# print(b)
# print(b.dtype)

# import pandas as pd
# t = pd.DataFrame(x)
# # print(t)
# # t['Gene_enco'] = t['Gene_enco'].apply()

<class 'dict'>
{'Target_ID': array(['Gene::1586', 'Gene::91', 'Gene::5291', ..., 'Gene::3782',
       'Gene::8510', 'Gene::6330'], dtype=object), 'ProtBERT_Features': 0       [0.10895072, 0.07753971, 0.14122498, -0.004359...
1       [0.07643488, 0.046613887, 0.11374605, 0.034627...
2       [0.079430476, 0.028320394, 0.066061325, 0.0013...
3       [0.13558188, 0.013845695, 0.12252106, 0.037885...
4       [0.11597116, 0.016289648, 0.10930617, 0.023096...
                              ...                        
1380    [0.026317561, 0.002467662, 0.088176705, 0.0322...
1381    [0.025081605, 0.011302358, 0.13916573, 0.03344...
1382    [0.06859535, -0.012777425, 0.09564611, 0.01458...
1383    [0.05675855, -0.017336804, 0.099945456, 0.0534...
1384    [0.08563626, -0.021550683, 0.13873681, 0.03547...
Name: ProtBERT_Features, Length: 1385, dtype: object, 'Gene_enco': array([1716., 1718., 1720., ...,   nan,   nan,   nan]), 'map_arr': array([   0,    1,    2, ..., 1382, 1383, 1384])}
dict_keys([

In [19]:
import pickle 
import numpy as np

with open('VEC_drug_feats.pkl', 'rb') as f:
    x = pickle.load(f, encoding='utf-8')
print(type(x))
print(x)
print(x.keys())
print(len(x['Drug_enco']))
print(type(x['Drug_enco']))
print(x['Drug_enco'])
x['Drug_enco'] = np.array(x['Drug_enco'])
print(x['Drug_enco'].dtype)
b = x['Drug_enco'].astype(int)
print(b)


<class 'dict'>
{'Drug_ID': array(['DB00672', 'DB00116', 'DB06663', ..., 'DB00610', 'DB08903',
       'DB00474'], dtype=object), 'Drug': array(['CCCNC(=O)NS(=O)(=O)C1=CC=C(C=C1)Cl',
       'C1C(NC2=C(N1)N=C(NC2=O)N)CNC3=CC=C(C=C3)C(=O)N[C@@H](CCC(=O)O)C(=O)O',
       'C1[C@H](CN2[C@@H]1C(=O)N[C@H](C(=O)N[C@@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C2=O)CC3=CC=CC=C3)CC4=CC=C(C=C4)OCC5=CC=CC=C5)CCCCN)CC6=CNC7=CC=CC=C76)C8=CC=CC=C8)OC(=O)NCCN',
       ..., 'C[C@@H]([C@@H](C1=CC(=CC=C1)O)O)N',
       'CN(C)CC[C@@](C1=CC=CC2=CC=CC=C21)([C@H](C3=CC=CC=C3)C4=C(N=C5C=CC(=CC5=C4)Br)OC)O',
       'CCC#CC(C)C1(C(=O)NC(=O)N(C1=O)C)CC=C'], dtype=object), 'Morgan_Features': 0       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, ...
4       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                              ...           

### float to int

In [6]:
import pandas as pd

df = pd.read_csv('vec_dev_origin.csv')
print(df.columns)
print(df[['gene_enco','drug_enco']])
df['gene_enco'] = df['gene_enco'].copy().astype(int)
df['drug_enco'] = df['drug_enco'].copy().astype(int)

print(df[['gene_enco','drug_enco']])
df.to_csv('vec_dev_origin.csv')


Index(['Target_ID', 'Drug_ID', 'Target', 'Drug', 'Y', 'NCBI_ID', 'gene_enco',
       'drug_enco'],
      dtype='object')
      gene_enco  drug_enco
0       12069.0      187.0
1       16051.0       70.0
2       11671.0      255.0
3        3134.0       41.0
4        2460.0       67.0
...         ...        ...
1922     5524.0     1510.0
1923    14649.0      735.0
1924     2985.0      321.0
1925     8339.0      529.0
1926     7309.0      224.0

[1927 rows x 2 columns]
      gene_enco  drug_enco
0         12069        187
1         16051         70
2         11671        255
3          3134         41
4          2460         67
...         ...        ...
1922       5524       1510
1923      14649        735
1924       2985        321
1925       8339        529
1926       7309        224

[1927 rows x 2 columns]


## data/vec/vec_dev_origin.csv에서 dev.txt에 있는 데이터만 vec_dev.csv로 저장

In [18]:
import pandas as pd
vec_og = pd.read_csv('vec_dev_origin.csv', index_col=0)
# print(vec_og.columns)
# print(vec_og)

vec = pd.read_csv('dev.txt', sep=' ',header=None)
vec.columns = ['gene_enco','drug_enco',"Y"]
print(vec.columns)
print(vec)


Index(['gene_enco', 'drug_enco', 'Y'], dtype='object')
      gene_enco  drug_enco  Y
0          8945         74  0
1          9832         10  0
2          5178       1401  1
3          6793       1325  1
4          5586       1260  1
...         ...        ... ..
1774       4054       1196  0
1775       7601       1018  0
1776      12128        229  0
1777      14697        694  1
1778      10950        557  1

[1779 rows x 3 columns]


In [27]:
vec.value_counts()

gene_enco  drug_enco  Y
12128      1287       0    2
4590       1282       0    2
           1071       0    2
18779      1627       0    2
12128      1251       0    2
                          ..
7128       486        1    1
           428        1    1
           408        0    1
           398        1    1
18925      739        0    1
Length: 1774, dtype: int64

In [1]:
import pandas as pd

# Read the vec_og DataFrame from 'vec_dev_origin.csv'
vec_og = pd.read_csv('vec_dev_origin.csv', index_col=0)

# Read the vec DataFrame from 'dev.txt'
vec = pd.read_csv('dev.txt', sep=' ', header=None)
vec.columns = ['gene_enco', 'drug_enco', 'Y']
print(vec['Y'].value_counts())

1    964
0    963
Name: Y, dtype: int64


In [15]:
import pickle
with open('VEC_target_feats.pkl', 'rb') as f:
    x = pickle.load(f, encoding='utf-8')
print(x.keys())
print(type((x['ProtBERT_Features'])))
print(x)

dict_keys(['Target_ID', 'ProtBERT_Features', 'Gene_enco', 'map_arr'])
<class 'pandas.core.series.Series'>
{'Target_ID': array(['Gene::1586', 'Gene::91', 'Gene::5291', ..., 'Gene::3782',
       'Gene::8510', 'Gene::6330'], dtype=object), 'ProtBERT_Features': 0       [0.10895072, 0.07753971, 0.14122498, -0.004359...
1       [0.07643488, 0.046613887, 0.11374605, 0.034627...
2       [0.079430476, 0.028320394, 0.066061325, 0.0013...
3       [0.13558188, 0.013845695, 0.12252106, 0.037885...
4       [0.11597116, 0.016289648, 0.10930617, 0.023096...
                              ...                        
1380    [0.026317561, 0.002467662, 0.088176705, 0.0322...
1381    [0.025081605, 0.011302358, 0.13916573, 0.03344...
1382    [0.06859535, -0.012777425, 0.09564611, 0.01458...
1383    [0.05675855, -0.017336804, 0.099945456, 0.0534...
1384    [0.08563626, -0.021550683, 0.13873681, 0.03547...
Name: ProtBERT_Features, Length: 1385, dtype: object, 'Gene_enco': array([1716., 1718., 1720., ...,   na

In [16]:
import pickle
with open('VEC_drug_feats.pkl', 'rb') as f:
    x = pickle.load(f, encoding='utf-8')
print(x.keys())
print(x)

dict_keys(['Drug_ID', 'Drug', 'Morgan_Features', 'Drug_enco'])
{'Drug_ID': array(['DB00672', 'DB00116', 'DB06663', ..., 'DB00610', 'DB08903',
       'DB00474'], dtype=object), 'Drug': array(['CCCNC(=O)NS(=O)(=O)C1=CC=C(C=C1)Cl',
       'C1C(NC2=C(N1)N=C(NC2=O)N)CNC3=CC=C(C=C3)C(=O)N[C@@H](CCC(=O)O)C(=O)O',
       'C1[C@H](CN2[C@@H]1C(=O)N[C@H](C(=O)N[C@@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C2=O)CC3=CC=CC=C3)CC4=CC=C(C=C4)OCC5=CC=CC=C5)CCCCN)CC6=CNC7=CC=CC=C76)C8=CC=CC=C8)OC(=O)NCCN',
       ..., 'C[C@@H]([C@@H](C1=CC(=CC=C1)O)O)N',
       'CN(C)CC[C@@](C1=CC=CC2=CC=CC=C21)([C@H](C3=CC=CC=C3)C4=C(N=C5C=CC(=CC5=C4)Br)OC)O',
       'CCC#CC(C)C1(C(=O)NC(=O)N(C1=O)C)CC=C'], dtype=object), 'Morgan_Features': 0       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, ...
4       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## 데이터셋별 클래스 분포 확인

In [3]:
import pandas as pd
import numpy as np

train = pd.read_csv('train.txt', sep=' ', header=None)
val = pd.read_csv('dev.txt', sep=' ', header=None)
test = pd.read_csv('test.txt', sep=' ', header=None)

print(train[2].value_counts())
print(val[2].value_counts())
print(test[2].value_counts())

0    6183
1    6148
Name: 2, dtype: int64
1    964
0    963
Name: 2, dtype: int64
1    1779
0    1745
Name: 2, dtype: int64


## protT5

In [1]:
from transformers import T5Tokenizer, T5EncoderModel
import re
import torch
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

# Load the tokenizer & model
tokenizer = T5Tokenizer.from_pretrained('Rostlab/ProstT5', do_lower_case=False) #.to(device)
model = T5EncoderModel.from_pretrained("Rostlab/ProstT5").to(device)

# only GPUs support half-precision currently; if you want to run on CPU use full-precision (not recommended, much slower)
model.full() if device=='cpu' else model.half()

# prepare your protein sequences/structures as a list. Amino acid sequences are expected to be upper-case ("PRTEINO" below) while 3Di-sequences need to be lower-case ("strctr" below).
sequence_examples = ["PRTEINO", "PRTEINO", "strct"]

# replace all rare/ambiguous amino acids by X (3Di sequences does not have those) and introduce white-space between all sequences (AAs and 3Di)
sequence_examples = [" ".join(list(re.sub(r"[UZOB]", "X", sequence))) for sequence in sequence_examples]

# add pre-fixes accordingly (this already expects 3Di-sequences to be lower-case)
# if you go from AAs to 3Di (or if you want to embed AAs), you need to prepend "<AA2fold>"
# if you go from 3Di to AAs (or if you want to embed 3Di), you need to prepend "<fold2AA>"
sequence_examples = [ "<AA2fold>" + " " + s if s.isupper() else "<fold2AA>" + " " + s
                      for s in sequence_examples
                    ]

# tokenize sequences and pad up to the longest sequence in the batch
ids = tokenizer.batch_encode_plus(sequence_examples, add_special_tokens=True, padding="longest",return_tensors='pt').to(device)

# generate embeddings
with torch.no_grad():
    embedding_repr = model(
              ids.input_ids, 
              attention_mask=ids.attention_mask
              )

# extract residue embeddings for the first ([0,:]) sequence in the batch and remove padded & special tokens, incl. prefix ([0,1:8]) 
emb_0 = embedding_repr.last_hidden_state[0,1:8] # shape (7 x 1024)
print(embedding_repr.last_hidden_state.shape)
print(embedding_repr.last_hidden_state)

# same for the second ([1,:]) sequence but taking into account different sequence lengths ([1,:6])
emb_1 = embedding_repr.last_hidden_state[1,1:6] # shape (5 x 1024)

# if you want to derive a single representation (per-protein embedding) for the whole protein
emb_0_per_protein = emb_0.mean(dim=0) # shape (1024)


Some weights of the model checkpoint at Rostlab/ProstT5 were not used when initializing T5EncoderModel: ['decoder.block.16.layer.0.SelfAttention.q.weight', 'decoder.block.17.layer.1.EncDecAttention.o.weight', 'decoder.block.1.layer.1.EncDecAttention.o.weight', 'decoder.block.17.layer.1.EncDecAttention.q.weight', 'decoder.block.15.layer.1.layer_norm.weight', 'decoder.block.8.layer.2.DenseReluDense.wi.weight', 'decoder.block.2.layer.0.layer_norm.weight', 'decoder.block.10.layer.0.SelfAttention.q.weight', 'decoder.block.5.layer.0.SelfAttention.k.weight', 'decoder.block.9.layer.0.layer_norm.weight', 'decoder.block.8.layer.0.SelfAttention.k.weight', 'decoder.block.3.layer.0.SelfAttention.v.weight', 'decoder.block.0.layer.0.layer_norm.weight', 'decoder.block.10.layer.2.DenseReluDense.wo.weight', 'decoder.block.15.layer.2.layer_norm.weight', 'decoder.block.23.layer.0.SelfAttention.q.weight', 'decoder.block.10.layer.0.SelfAttention.v.weight', 'decoder.block.6.layer.2.layer_norm.weight', 'decod

torch.Size([3, 9, 1024])
tensor([[[-1.7776e-02, -9.8267e-03, -2.6428e-02,  ...,  3.0807e-02,
          -8.5831e-03, -1.2054e-02],
         [-1.1469e-01, -6.5796e-02,  5.4626e-02,  ...,  3.8574e-01,
          -8.4961e-02,  4.3976e-02],
         [-1.4734e-01, -2.0776e-01, -4.3042e-01,  ...,  3.9648e-01,
          -1.1389e-01, -7.5073e-02],
         ...,
         [-2.5903e-01, -2.9434e-02,  3.0823e-02,  ...,  5.3986e-02,
           4.7485e-02, -6.8665e-02],
         [ 6.6223e-02,  1.3176e-02,  3.8574e-02,  ...,  1.2268e-01,
          -6.2195e-02, -1.1792e-01],
         [ 3.4809e-03, -6.4774e-03,  6.7329e-03,  ...,  3.4668e-02,
           1.7563e-02,  5.0446e-02]],

        [[-1.7776e-02, -9.8267e-03, -2.6428e-02,  ...,  3.0807e-02,
          -8.5831e-03, -1.2054e-02],
         [-1.1469e-01, -6.5796e-02,  5.4626e-02,  ...,  3.8574e-01,
          -8.4961e-02,  4.3976e-02],
         [-1.4734e-01, -2.0776e-01, -4.3042e-01,  ...,  3.9648e-01,
          -1.1389e-01, -7.5073e-02],
         ...,


In [3]:
embedding_repr.last_hidden_state.shape

torch.Size([2, 9, 1024])

In [19]:
print(emb_0_per_protein)
print(emb_0_per_protein.shape)

tensor([-0.1263, -0.0712,  0.0474,  ...,  0.2103, -0.0312, -0.0347],
       device='cuda:0', dtype=torch.float16)
torch.Size([1024])


In [8]:
emb_1_per_protein = emb_1.mean(dim=0) # shape (1024)
print(emb_1_per_protein)
print(emb_1_per_protein.shape)

tensor([ 0.1025, -0.0829,  0.0972,  ...,  0.0512,  0.1245,  0.1018],
       device='cuda:0', dtype=torch.float16)
torch.Size([1024])


In [17]:
embedding_repr.last_hidden_state[0,1:].shape

torch.Size([8, 1024])